### ISSUE TITLE
Adding a salt to the hashing process

### ISSUE THREAD

**Issue by wojake** [GemWallet/gemwallet-extension#29]
https://github.com/GemWallet/gemwallet-extension/blob/master/packages/extension/src/utils/seed.ts#L9
![image](https://user-images.githubusercontent.com/87929946/163683592-158deea7-9725-4ea4-96ac-afc3dcc536c5.png)
I'm not familiar with securing wallet credentials but shouldn't there be a unique salt for each hashed credential.

@WietseWind knows more about securing wallet credentials than I am, should credentials like a seed phrase include a salt if it's being kept locally on a web extension?

**Comment by WietseWind** [comment]
@wojake It's being passed to this function:
https://github.com/GemWallet/gemwallet-extension/blob/6f2fe07f22fe9ca93d5f098829eb3649b836beac/packages/extension/src/utils/crypto.ts#L3

Which uses `CryptoJS.AES.encrypt`. 

Switching to e.g. `aes-256-gcm` would offer more security, indeed.
https://github.com/XRPL-Labs/XUMM-Push-Backend/blob/main/crypto.js

**Comment by FlorianBouron** [comment]
@wojake thanks for having a look at the code, really appreciate it!
@WietseWind thanks for the reference, let me have a look at it, I need to understand the difference between your implementation and mine.
Where would you store the iv in that case? Seems that it has to be stored in the chrome extension anyway. Would it really bring additional security instead of using `CryptoJS.AES.encrypt` directly?
@all-contributors please add @wojake for security
@all-contributors please add @WietseWind for security and example

**Comment by FlorianBouron** [comment]
@all-contributors please add @wojake for security

**Comment by FlorianBouron** [comment]
@all-contributors please add @WietseWind for security and example

**Comment by FlorianBouron** [comment]
Thanks @wojake for the hint, I am going to add the improvement - starting to work on it.

**Comment by FlorianBouron** [comment]
I am closing this issue as the code provided works only for Node.js (backend) using the native "crypto" library.
Currently cyrpojs does not support a GCM encryption: https://cryptojs.gitbook.io/docs/#block-modes-and-padding
I was exploring what the native crypo web API provides:
https://developer.mozilla.org/en-US/docs/Web/API/AesGcmParams
As you can see the maximum AES GCM used would be: `128` bits keeping a default AES-256-CBC seems better in my option.
Following the initial issue referring to "salt" cryptojs is generating a unique IV for each encryption - which means that there is a different "salt".
I hope it answer your concern @wojake .
